language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.3
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.5
  - 3.0.3
  - 3.1.0
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - jruby-head
  - truffleruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
